swagger: "2.0"
info:
  description: Search for personal financial transactions record by diverse data source
  version: "1.0.0"
  title: Individual Financial Database
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /transactions:
    get:
      operationId: "transactions.read"
      tags:
        - "Transaction"
      summary: "Financial transaction data structure supported by the server application"
      description: "Read the list of transaction"
      responses:
        200:
          description: "Successful read transaction list operation"
          schema:
            type: "array"
            items:
              properties:
                identifier:
                  type: "string"
                transactionDate:
                  type: "string"
                currency:
                  type: "string"
                amount:
                  type: "string"
                direction:
                  type: "string"
                category:
                  type: "string"
                source:
                  type: "string"
                transactionTime:
                  type: "string"

paths:
  /transactions:
    get:
      operationId: "transactions.read"
      tags:
        - "Transaction"
      summary: "Financial transaction data structure supported by the server application"
      description: "Read the list of transaction"
      responses:
        200:
          description: "Successful read transaction list operation"
          schema:
            type: "array"
            items:
              properties:
                identifier:
                  type: "string"
                transactionDate:
                  type: "string"
                currency:
                  type: "string"
                amount:
                  type: "string"
                direction:
                  type: "string"
                category:
                  type: "string"
                source:
                  type: "string"
                transactionTime:
                  type: "string"
